DEVICE     = atmega2560
CLOCK      = 16000000
PROGRAMMER = -c wiring -b 115200 -P COM3 -D
OBJECTS    = lcd.o speedDisplay.o ultrasonic.o
FUSES      = -U hfuse:w:0xD8:m -U lfuse:w:0xFF:m -U efuse:w:0xFD:m

# Tune the lines below only if you know what you are doing:

AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)
COMPILE = avr-gcc -Wall -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)
LDFLAGS = -Wl,-u,vfprintf -lprintf_flt -lm

# symbolic targets:
all:	main.hex

.c.o:
	$(COMPILE) -c $< -o $@
 
.S.o:
	$(COMPILE) -x assembler-with-cpp -c $< -o $@
# "-x assembler-with-cpp" should not be necessary since this is the default
# file type for the .S (with capital S) extension. However, upper case
# characters are not always preserved on Windows. To ensure WinAVR
# compatibility define the file type manually.

.c.s:
	$(COMPILE) -S $< -o $@

flash:	all
	$(AVRDUDE) -U flash:w:main.hex:i

fuse:
	$(AVRDUDE) $(FUSES)

# Xcode uses the Makefile targets "", "clean" and "install"
install: flash fuse

# if you use a bootloader, change the command below appropriately:
load: all
	bootloadHID main.hex

clean:
	rm -f main.hex main.elf $(OBJECTS)

# file targets:
main.elf: $(OBJECTS)
	$(COMPILE) -o main.elf $(OBJECTS) $(LDFLAGS)

main.hex: main.elf
	rm -f main.hex
	avr-objcopy -j .text -j .data -O ihex main.elf main.hex
	avr-size --format=avr --mcu=$(DEVICE) main.elf
# If you have an EEPROM section, you must also create a hex file for the
# EEPROM and add it to the "flash" target.

# Targets for code debugging and analysis:
disasm:	main.elf
	avr-objdump -d main.elf

cpp:
	$(COMPILE) -E main.c

test: test.hex
	$(AVRDUDE) -U flash:w:test.hex:i

enable: enable.hex
	$(AVRDUDE) -U flash:w:enable.hex:i
enable.elf: enable.o lcd.o
	$(COMPILE) -o enable.elf enable.o lcd.o
enable.hex: enable.elf
	rm -f enable.hex
	avr-objcopy -j .text -j .data -O ihex enable.elf enable.hex
	avr-size --format=avr --mcu=$(DEVICE) enable.elf

